apiVersion: apps/v1 # Specify the API version of kubernetes
kind: Deployment # Specify this component of kubernetes is deployment
metadata: # Metadata for this component
  name: book-catalog-deployment # Name of the deployment
spec: # Specification for this deployment
  replicas: 1 # Number of pods to deploy
  selector: # Define how kubernetes will find the pods for this deployment
    matchLabels: # Specify labels to identify pods
      app: book-catalog # Kubernetes will look for the pods with app: book-catalog
  template: # Define blueprint for pod
    metadata: # Metadata for the pod
      labels: # Labels for the pod
        app: book-catalog
    spec: # Specification for the pod
      containers: # List of containers for each pod
      - name: book-catalog # Name of the container
        image: aashisharyal/sit722week6task2d:1.1.1 # Docker image that the container will use
        ports: # Ports to be exposed on the container
        - containerPort: 80 # The app in this container will be hosted on this port
        env: # Defines environment variables
        - name: DATABASE_URL # Name of an environment variable
          value: "postgresql://sit722_6_2p_8ttk_user:1JgIICt78TVvLHIlXe2fxoHVvl5FhDT3@dpg-crh5ki08fa8c738sgf80-a.oregon-postgres.render.com/sit722_6_2p_8ttk"
          # Value of the environment variable


---

apiVersion: v1 # Specify the API version of kubernetes
kind: Service # Specify this component of kubernetes is service
metadata: # Metadata for this component
  name: book-catalog-service # Name of the service
spec: # Specification for this dervice
  selector: # Defines which pods this service will target
    app: book-catalog # This Service will select and forward traffic to the pods labeled app: book-catalog
  type: NodePort  # Expose port of pod externally
  ports: # Defines the ports that the service will expose
    - protocol: TCP # Protocol for this service
      port: 80 # Port of the pod
      targetPort: 80 # The container's port
      nodePort: 30001 # External port