apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: aashisharyal/sit722week6task2d:1.1.1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_6_2p_8ttk_user:1JgIICt78TVvLHIlXe2fxoHVvl5FhDT3@dpg-crh5ki08fa8c738sgf80-a.oregon-postgres.render.com/sit722_6_2p_8ttk"


---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: NodePort  # Expose it externally via a port
  ports:
    - protocol: TCP
      port: 80              # Port inside the container
      targetPort: 80         # The container's port
      nodePort: 30001        # External port (use a port between 30000-32767)